import { CaptionTemplate, CaptionTemplateId } from '../types/timeline';

export interface CaptionPresetDefinition extends CaptionTemplate {
  previewText: string;
  category: 'viral' | 'minimal' | 'stylized';
  tags: string[];
}

export const CAPTION_PRESETS: Record<CaptionTemplateId, CaptionPresetDefinition> = {
  hormozi: {
    id: 'hormozi',
    name: 'Alex Hormozi (Green Pill)',
    description: 'Heavy bold uppercase text with active green pill capsule and dark outline',
    font_family: 'Montserrat, "Space Grotesk", sans-serif',
    font_size: 38,
    font_color: '#FFFFFF',
    highlight_color: '#00FF66',
    emphasis_color: '#FFE000',
    stroke_color: '#000000',
    stroke_width: 5.5,
    background: false,
    background_color: null,
    word_box: true,
    word_box_color: '#00BF49',
    animation: 'karaoke',
    word_pop: true,
    bounce_intensity: 0.22,
    emoji: true,
    uppercase: true,
    shadow: true,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.74,
    previewText: 'THIS SECRET IS INSANE',
    category: 'viral',
    tags: ['hormozi', 'pill', 'bold', 'green', 'high-converting'],
  },

  beast: {
    id: 'beast',
    name: 'MrBeast (Punchy Bounce)',
    description: 'High-energy scale bounce on active words with alternating primary colors',
    font_family: 'Bangers, Montserrat, sans-serif',
    font_size: 44,
    font_color: '#FFFFFF',
    highlight_color: '#FFE600',
    emphasis_color: '#FF2D55',
    stroke_color: '#000000',
    stroke_width: 6.5,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'bounce',
    word_pop: true,
    bounce_intensity: 0.35,
    emoji: true,
    uppercase: true,
    shadow: true,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.70,
    alternating_colors: ['#FFE600', '#FF2D55', '#00F0FF', '#26DE81'],
    previewText: 'I GAVE AWAY $1,000,000',
    category: 'viral',
    tags: ['beast', 'punchy', 'bounce', 'alternating', 'youtube'],
  },

  mrbeast: {
    id: 'mrbeast',
    name: 'MrBeast (Classic Yellow)',
    description: 'Classic yellow text with red pop highlights and heavy drop shadow',
    font_family: 'Bangers, Montserrat, sans-serif',
    font_size: 42,
    font_color: '#FFFF00',
    highlight_color: '#FF2D2D',
    emphasis_color: '#FFFFFF',
    stroke_color: '#000000',
    stroke_width: 6,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    bounce_intensity: 0.25,
    emoji: true,
    uppercase: true,
    shadow: true,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.70,
    alternating_colors: ['#FF2D2D', '#00F0FF', '#FFE600'],
    previewText: 'WATCH UNTIL THE END',
    category: 'viral',
    tags: ['beast', 'yellow', 'red', 'youtube'],
  },

  minimal: {
    id: 'minimal',
    name: 'Minimal Clean (Pill Fade)',
    description: '2-3 words per card with soft rounded pill background and subtle fade transitions',
    font_family: 'Inter, system-ui, sans-serif',
    font_size: 27,
    font_color: '#FFFFFF',
    highlight_color: '#FFFFFF',
    emphasis_color: '#38BDF8',
    stroke_color: null,
    stroke_width: 0,
    background: true,
    background_color: 'rgba(5, 8, 15, 0.72)',
    word_box: false,
    word_box_color: null,
    animation: 'fade',
    word_pop: false,
    fade_transition: true,
    emoji: false,
    uppercase: false,
    shadow: false,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.80,
    previewText: 'clean subtle elegance',
    category: 'minimal',
    tags: ['minimal', 'pill', 'fade', 'modern', 'clean'],
  },

  tiktok: {
    id: 'tiktok',
    name: 'TikTok Pink Pop',
    description: 'Vibrant TikTok pink pop highlights with crisp outline',
    font_family: 'Inter, system-ui, sans-serif',
    font_size: 34,
    font_color: '#FFFFFF',
    highlight_color: '#FE2C55',
    emphasis_color: '#FE2C55',
    stroke_color: '#000000',
    stroke_width: 4.5,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    bounce_intensity: 0.22,
    emoji: true,
    uppercase: false,
    shadow: true,
    glow: false,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.78,
    previewText: 'viral tiktok aesthetic',
    category: 'viral',
    tags: ['tiktok', 'pink', 'reels', 'shorts'],
  },

  neon: {
    id: 'neon',
    name: 'Cyber Neon Glow',
    description: 'Glowing cyan text with magenta highlights and dark neon aura',
    font_family: 'Space Grotesk, Montserrat, sans-serif',
    font_size: 36,
    font_color: '#00FFFF',
    highlight_color: '#FF00FF',
    emphasis_color: '#FF00FF',
    stroke_color: '#002A6B',
    stroke_width: 3.5,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    bounce_intensity: 0.2,
    emoji: false,
    uppercase: false,
    shadow: false,
    glow: true,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.76,
    alternating_colors: ['#FF00FF', '#00FFFF', '#FFFF00'],
    previewText: 'CYBERPUNK NEON GLOW',
    category: 'stylized',
    tags: ['neon', 'cyber', 'glow', 'magenta', 'cyan'],
  },

  podcast: {
    id: 'podcast',
    name: 'Podcast Gold',
    description: 'Warm gold accent with dark semi-transparent card container',
    font_family: 'Inter, system-ui, sans-serif',
    font_size: 28,
    font_color: '#FFFFFF',
    highlight_color: '#FFB800',
    emphasis_color: '#FFB800',
    stroke_color: '#1A1A1A',
    stroke_width: 2,
    background: true,
    background_color: 'rgba(20, 24, 33, 0.85)',
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: false,
    emoji: false,
    uppercase: false,
    shadow: false,
    glow: false,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.80,
    previewText: 'The unspoken truth about business',
    category: 'minimal',
    tags: ['podcast', 'interview', 'gold', 'subtle'],
  },

  default: {
    id: 'default',
    name: 'Viral Pop (Default)',
    description: 'Classic punchy word-by-word captions with yellow pop highlight',
    font_family: 'Montserrat, "Space Grotesk", sans-serif',
    font_size: 34,
    font_color: '#FFFFFF',
    highlight_color: '#FFE000',
    emphasis_color: '#FFE000',
    stroke_color: '#000000',
    stroke_width: 4.5,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    bounce_intensity: 0.22,
    emoji: true,
    uppercase: false,
    shadow: true,
    glow: false,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.80,
    previewText: 'Watch this mindblowing hack',
    category: 'viral',
    tags: ['default', 'pop', 'yellow', 'karaoke'],
  },
};

export const CAPTION_PRESETS_LIST: CaptionPresetDefinition[] = Object.values(CAPTION_PRESETS);

export function getCaptionPreset(id: string): CaptionPresetDefinition {
  if (id === 'beast') return CAPTION_PRESETS.beast;
  return CAPTION_PRESETS[id as CaptionTemplateId] || CAPTION_PRESETS.default;
}
