import { CaptionTemplate, CaptionTemplateId } from '../../types/timeline';

export const SUPOCLIP_CAPTION_TEMPLATES: Record<CaptionTemplateId, CaptionTemplate> = {
  default: {
    id: 'default',
    name: 'Default (Viral Pop)',
    description: 'Punchy word-by-word captions with yellow pop highlight and emojis',
    font_family: 'Montserrat, "Space Grotesk", sans-serif',
    font_size: 32,
    font_color: '#FFFFFF',
    highlight_color: '#FFE000', // Bright yellow active word
    emphasis_color: '#FFE000',
    stroke_color: '#000000',
    stroke_width: 4,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    emoji: true,
    uppercase: false,
    shadow: true,
    glow: false,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.80,
  },

  hormozi: {
    id: 'hormozi',
    name: 'Alex Hormozi (Green Pill)',
    description: 'Bold green highlight with a pill behind the active word',
    font_family: 'Montserrat, "Space Grotesk", sans-serif',
    font_size: 38,
    font_color: '#FFFFFF',
    highlight_color: '#00FF66', // Bright green
    emphasis_color: '#FFE000',
    stroke_color: '#000000',
    stroke_width: 5,
    background: false,
    background_color: null,
    word_box: true,
    word_box_color: '#00BF49', // Green pill box behind active word
    animation: 'karaoke',
    word_pop: true,
    emoji: true,
    uppercase: true,
    shadow: true,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.74,
  },

  mrbeast: {
    id: 'mrbeast',
    name: 'MrBeast (Classic Yellow)',
    description: 'Large yellow text with red pop highlights and emojis',
    font_family: 'Bangers, Montserrat, sans-serif',
    font_size: 42,
    font_color: '#FFFF00', // Yellow base
    highlight_color: '#FF2D2D', // Red pop
    emphasis_color: '#FFFFFF',
    stroke_color: '#000000',
    stroke_width: 6,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    bounce_intensity: 0.25,
    emoji: true,
    uppercase: true,
    shadow: true,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.70,
    alternating_colors: ['#FF2D2D', '#00F0FF', '#FFE600'],
  },

  beast: {
    id: 'beast',
    name: 'MrBeast (Punchy Bounce)',
    description: 'High-energy scale bounce on active words with alternating primary colors',
    font_family: 'Bangers, Montserrat, sans-serif',
    font_size: 44,
    font_color: '#FFFFFF',
    highlight_color: '#FFE600',
    emphasis_color: '#FF2D55',
    stroke_color: '#000000',
    stroke_width: 6.5,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'bounce',
    word_pop: true,
    bounce_intensity: 0.35,
    emoji: true,
    uppercase: true,
    shadow: true,
    glow: false,
    max_words_per_line: 3,
    position_x: 0.5,
    position_y: 0.70,
    alternating_colors: ['#FFE600', '#FF2D55', '#00F0FF', '#26DE81'],
  },

  tiktok: {
    id: 'tiktok',
    name: 'TikTok Pink',
    description: 'Signature TikTok style with vibrant pink pop highlights',
    font_family: 'Inter, system-ui, sans-serif',
    font_size: 34,
    font_color: '#FFFFFF',
    highlight_color: '#FE2C55', // TikTok pink
    emphasis_color: '#FE2C55',
    stroke_color: '#000000',
    stroke_width: 4,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    emoji: true,
    uppercase: false,
    shadow: true,
    glow: false,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.78,
  },

  neon: {
    id: 'neon',
    name: 'Cyber Neon',
    description: 'Glowing cyan text with magenta highlights and dark blue shadow',
    font_family: 'Montserrat, "Space Grotesk", sans-serif',
    font_size: 36,
    font_color: '#00FFFF', // Cyan
    highlight_color: '#FF00FF', // Magenta
    emphasis_color: '#FF00FF',
    stroke_color: '#002A6B',
    stroke_width: 3,
    background: false,
    background_color: null,
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: true,
    emoji: false,
    uppercase: false,
    shadow: false,
    glow: true,
    max_words_per_line: 4,
    position_x: 0.5,
    position_y: 0.76,
  },

  minimal: {
    id: 'minimal',
    name: 'Minimal Dark',
    description: 'Clean, subtle captions with a soft translucent background pill',
    font_family: 'Inter, system-ui, sans-serif',
    font_size: 26,
    font_color: '#FFFFFF',
    highlight_color: '#FFFFFF',
    emphasis_color: null,
    stroke_color: null,
    stroke_width: 0,
    background: true,
    background_color: 'rgba(0, 0, 0, 0.65)',
    word_box: false,
    word_box_color: null,
    animation: 'fade',
    word_pop: false,
    emoji: false,
    uppercase: false,
    shadow: false,
    glow: false,
    max_words_per_line: 6,
    position_x: 0.5,
    position_y: 0.82,
  },

  podcast: {
    id: 'podcast',
    name: 'Podcast Gold',
    description: 'Warm gold accent with dark semi-transparent background',
    font_family: 'Inter, system-ui, sans-serif',
    font_size: 28,
    font_color: '#FFFFFF',
    highlight_color: '#FFB800', // Warm gold
    emphasis_color: '#FFB800',
    stroke_color: '#1A1A1A',
    stroke_width: 2,
    background: true,
    background_color: 'rgba(26, 26, 26, 0.85)',
    word_box: false,
    word_box_color: null,
    animation: 'karaoke',
    word_pop: false,
    emoji: false,
    uppercase: false,
    shadow: false,
    glow: false,
    max_words_per_line: 5,
    position_x: 0.5,
    position_y: 0.80,
  },
};

export function getCaptionTemplate(id: CaptionTemplateId): CaptionTemplate {
  return SUPOCLIP_CAPTION_TEMPLATES[id] || SUPOCLIP_CAPTION_TEMPLATES.default;
}
